### ISSUE TITLE
Переделать компонент toogle..

### ISSUE THREAD

**Issue by mixrich** [mixrich/news#13]
Мне совершенно не нравится его текущая реализация - он плохо скейлится от размера окружающего шрифта, пропорцию блока справа практически невозможно универсально поддерживать... http://prntscr.com/cxvh29

Возможно я уйду от label в сторону обычного JS обработчика для кнопки, чтобы просто сам элемент с точки зрения верстки был проще. В таком случае этот toogle вырвется из контекста формы и его придется валидировать через JS, что не есть хорошо...

Либо просто переделаю верстку элемента, чтобы проще было управлять его стилями и поведением... Пока не нашел подходящего решения

**Comment by Ingiboy** [comment]
Элемент не будет использоваться
