### ISSUE TITLE
Описать стили блоков результатов поиска

### ISSUE THREAD

**Issue by mixrich** [mixrich/news#19]
Результаты поиска обернули в ссылку. Нужен какой-то hover эффект при наведении на блок результата. Сейчас я просто оставил текст подчеркнутым 

http://prntscr.com/d0d5mj

**Comment by Ingiboy** [comment]
ХЗ, в стиле это или нет, я бы фон сереньким делал

**Comment by mixrich** [comment]
Да, это стилями задается. Тёму бы подключить к этому вопросу
