### ISSUE TITLE
Уменьшить лимит картинок для слайдера до 2

### ISSUE THREAD

**Issue by Ingiboy** [mixrich/news#24]
Сейчас навигация показывается при 4 и более фото.

Задание на 5+: сделать более юзабельно в кэдиторе :)

**Comment by mixrich** [comment]
Теперь слайдер может состоять хоть из одной фотки - у него не будет стрелок затемнения по бокам останутся, но это корректно. Если фотки 2 и более, то все теперь отлично

Обнови app.js файл в проекте
