### ISSUE TITLE
Изменить структуру спецвставок

### ISSUE THREAD

**Issue by Ingiboy** [mixrich/news#25]
```
<div class="quote-container quote_image">
	<div class="quote">
		<div class="quote__author clearfix">
			**<div class="quote__author__photo">**
				<img class="quote__author__photo" src="images/persons/Petlina_N.jpg" alt="" />
			**</div>**
			<div class="quote__author__info">
				**<div class="quote__author__name">**Надежда<br/>Петлина**</div>**
				**<div class="quote__author__position">**председатель Совета ветеранов ТЭЛЗ**</div>**
			</div>
		</div>
		<div class="quote__content">
			<p>Когда я в 1965 году пришла на завод, наши с Марией Антоновной линейки стояли рядышком. Она была лучшим специалистом. Настолько все делала искусно, что у нее ничего не трескалось, не выбрасывалось в брак. Если уж они перегоревшую лампу оживляли, то «ножку», которая на пол упала, подберут обязательно. Ее можно наладить, вновь запаять.
			</p>
			<p>А еще Мария Антоновна всегда была очень скромной, положительной. Никогда не нагрубит, если спросишь совета — подойдет, расскажет.
			</p>
			<p>Ее портреты часто висели на досках почета. Тогда это была очень большая честь. Надо было не только хорошо работать, а еще и общественную нагрузку нести. А портреты самых лучших работников вывешивали на доске почета возле завода.
			</p>
		</div>
	</div>
</div>

```

**Comment by Ingiboy** [comment]
Для того, чтобы во вставляемом шаблоне в кэдиторе нужные поля можно было редактировать, эти поля должны заключаться в div, другие не подходят.
С картинкой то же самое - её надо взять в несущий див со своим классом, чтобы его можно было сделать редактируемым

**Comment by Ingiboy** [comment]
То, что я вставил, работает в кэдиторе как надо

**Comment by mixrich** [comment]
Вопрос в том, чтобы заменить существующий блок этим и чуть чуть подправить стили, чтобы все работало?

**Comment by mixrich** [comment]
Вопрос только для этого блока или для каких-то еще?

**Comment by Ingiboy** [comment]
заменить этим
потому что в кэдиторе можно редактировать только то поле, которое заключено в див
два поля в один див нельзя, и нельзя в див поместить поле и еще див, в котором тоже поле

в плагине указываются иды или классы дивов, контент которых может редактироваться, в примере сверху в элементах:
— `<div class="quote__author__photo">` редактируется картинка, и я указываю ограничения, что там может быть только имг с только определенными параметрами
— `<div class="quote__author__name">` и `<div class="quote__author__position">` редактируются, соответственно, только текстовые строки, в имени разрешен тэг br
— `<div class="quote__content">` - редактируется текст, разрешены тэги a b br p

и так у всех трех блоков

**Comment by Ingiboy** [comment]
фактически, редактируемый фрагмент должен быть помещев див так же, как в форме текст - в текстареа

**Comment by mixrich** [comment]
Заменил все три блока цитаты на твою верстку на дивах, чуть чуть подправил стили. Смотри изменения на моем сайте. Класс для img фотки пришлось убрать.
