### ISSUE TITLE
Уменьшить font-weight у верхнего и нижнего меню с 700 до 600

### ISSUE THREAD

**Issue by Ingiboy** [mixrich/news#27]
Из-за замены шрифта слишком жирно вышло.
В нижнем меню - тоже.

![image](https://cloud.githubusercontent.com/assets/20064139/20094872/b9f581ca-a5d5-11e6-99ad-20becc5e7a71.png)

**Comment by Ingiboy** [comment]
На заголовках статейных блоков на главной (и остальных, где они используются) - уменьшить до 500

**Comment by mixrich** [comment]
Залил CSS
