### ISSUE TITLE
У блока-анонса ограничить величину заголовка 2 строками, добавив «...» если строк больше

### ISSUE THREAD

**Issue by Ingiboy** [mixrich/news#28]
Subj.
![image](https://cloud.githubusercontent.com/assets/20064139/20106804/f51cc6cc-a608-11e6-8df3-1a70587e1747.png)

**Comment by mixrich** [comment]
Пока без многоточия, думаю над этим

**Comment by mixrich** [comment]
С многоточием так и не нашел решения. Есть варианты, как это сделать, но это сопровождается использованием либо очень нестандартных свойств CSS, либо не имеет адаптивности.
Предлагаю оставить как есть сейчас, без многоточия, зато быть полностью уверенными, что ничего не сломается на каком-либо браузере и подумать над решением позже.

**Comment by mixrich** [comment]
Хотя не, есть решение, залил. Работает только в web-kit браузерах (Chromium based, Safari).
В других браузерах (у FF свой движок, у IE свой) текст просто будет скрываться как и раньше.

**Comment by Ingiboy** [comment]
У релапа как-то сделано многоточие.

Пример: https://obzor.westsib.ru/news/511083---elku-foto внизу рекомендации

Код:
![image](https://cloud.githubusercontent.com/assets/20064139/20300639/a6312fea-ab52-11e6-829b-f5c4717b79b3.png)

**Comment by mixrich** [comment]
У них на JS решение. Пока 8 блоков - ниче, а вот когда на странице будет 30+, начнет тупить при ресайзе окна

**Comment by Ingiboy** [comment]
А если забить на ресайз и делать операцию только для подгруженных блоков?
Первый раз - при загрузке страницы, потом - при подгрузке каждой следующей порции _только_ для этой порции?
Хотя может быть все равно плохое решение

**Comment by mixrich** [comment]
Без ресайза проще, только все равно надо думать о том, что мы не в мобиле сейчас, понимать в каком мы именно блоке находимся. Рабочее решение будет конечно, только вот если вы "Будете следить за длиной заголовка", то надо ли оно потом будет?

**Comment by Ingiboy** [comment]
Да, к черту тогда
