### ISSUE TITLE
Внедрить слайдер на страницу со статьей

### ISSUE THREAD

**Issue by mixrich** [mixrich/news#3]
Скорее всего просто так вставить его не получится, ибо он должен быть шире контента.

Попробовать задавать ему отрицательный margin в пропорции, чтобы он всегда был визуально на всю ширину, либо ограничивать каждый элемент контента статьи по ширине, чтобы тело статьи было на всю ширину, контент max-width 820px, margin 0 auto.
Не забывать про редактор, в котором новости будут делаться (Keditor или как там его...). Это должно быть удобно для контентщиков, но и не сильно геморно по верстке, чтобы не плыли кроссбраузерные баги

**Comment by Ingiboy** [comment]
Тёма, по-моему, на встрече предложил аппаратный способ вставки слайдера.
Пример:
1. в CKEditor у нас будет такая структура

[div class="articleBody"]
...some content...
[slider][/slider]
...some content...
[/div]
1. В статье на сайте можно делать программно разрыв статьи в месте имплементации слайдера:

[div class="articleBody"]
...some content...
[/div] - насильственное закрытие articleBody

[slider][/slider]

[div class="articleBody"] - повторное открытие articleBody
...some content...
[/div]

Единственный у меня вопрос - можно ли сделать слайдер именно тэгом `[slider]` или еще каким-то оригинальным. пусть он не отображается в html-е вообще, но будет для меня меткой приложения регулярного выражения для разрыва?

**Comment by mixrich** [comment]
Если этот разрыв будет программным, то нужно подумать над тем, как именно это будет происходить, чтобы и в редакторе было норм работать, и на страницу клиенту отдавалось в нужном виде, но решение интересное.

Что касается тега, то вообще можно сделать свой кастомный тег slider, только нужно будет его в JS создать (одна строка) и стили указать. 
А строка <div class="slider"> или даже просто class="slider" не будет являться нужным триггером?

**Comment by Ingiboy** [comment]
> или даже просто class="slider" не будет являться нужным триггером?

Я подумаю, может хтмл-коммент буду добавлять. Для автоматического безгеморройного разрыва мне нужна прямо в тексте какая-то уникальная последовательность символов. Т.е. не яваскриптом созданное, а прямо в тексте существующая. И тогда я просто делаю замену `<slider>` на `</div><slider>` и `</slider>` на `</slider><div class="articleBody">`

**Comment by Ingiboy** [comment]
Блин. я забыл о своем же предложении сделать отступы.
![картинка](http://obzor.westsib.ru/data/image/photo_2016-09-28_12-28-20.jpg)

**Comment by Ingiboy** [comment]
В общем, либо можно программно рвать, либо сделать как на картинке. Что лучше и логичнее?

**Comment by mixrich** [comment]
Сейчас для всех элементов статьи задана максимальная ширина и выравнивание по центру. Слайдер же выравнивается на всю ширину. Ничего разрывать не нужно сейчас, все сделано на основании твоего предложения - отступы через стили
