### ISSUE TITLE
В CKEditor заголовок H3+флерон выглядит некорректно

### ISSUE THREAD

**Issue by Ingiboy** [mixrich/news#30]
Во время вставки и потом на сайте - все ок

![image](https://cloud.githubusercontent.com/assets/20064139/20107560/81cbf00a-a60b-11e6-90aa-3bd2cd9252d9.png)

**Comment by mixrich** [comment]
Хм, Yandex, Chrome, FF - все ок http://prntscr.com/d9i283

Скажи версию браузера, в котором делаете

**Comment by Ingiboy** [comment]
Развернутый коммент:
Когда при редактировании добавляешь этот элемент, то он выглядит правильно. После сохранения статьи на сайте он тоже выглядит хорошо. А когда открываешь на редактирование текст, где УЖЕ содержится этот элемент, то он выглядит как я написал.
Для проверки добавь в текстареа код элемента и открой страничку с кэдитором

**Comment by Ingiboy** [comment]
Довесок: вставил в кэдитор в режиме исходного кода
```
<div class="divider-hat"></div>
```
и
```
<div class="divider-moustache"></div>
```
![image](https://cloud.githubusercontent.com/assets/20064139/20463797/dd6495dc-af6d-11e6-9984-22ef371c521e.png)

Та же беда. И усы цветные)

**Comment by mixrich** [comment]
Хах, в чем была суть:
Ckeditor видит пустую div'ку и думает "Вай вай вай, как же так? Как теперь этот хороший человек будет текс писать внутри нее? Надо ему помочь, вставлю ка я туда <br>, чтобы было место откуда начинать писать контент элемента". Когда сохранял, ckeditor видел, что контента нет, и удалял <br> из элементов, чтобы ничего не поломать.

Вот наличие этого <br> и ломало элементы в редакторе.

Обновляй CSS

**Comment by Ingiboy** [comment]
Усы в чорный покрась, плз) и закроем

**Comment by mixrich** [comment]
Готово
