### ISSUE TITLE
По нажатию на кнопку поиска ставить курсор в текстовое поле 

### ISSUE THREAD

**Issue by Ingiboy** [mixrich/news#31]
![image](https://cloud.githubusercontent.com/assets/20064139/20108705/8790ae3c-a60f-11e6-88b0-25c456b1d444.png)

**Comment by mixrich** [comment]
Разметку чуть чуть обновить для формы поиска http://prntscr.com/d6a7ii
CSS естественно тоже обновить
App.js Тоже обновить надо будет, ибо там добавил закрытие поиска по нажатию на клавишу ESC

**Comment by Ingiboy** [comment]
Обновил, кеш почистил, не срабатывает. Хром, Вин7

**Comment by Ingiboy** [comment]
![image](https://cloud.githubusercontent.com/assets/20064139/20237534/92f8aeb4-a907-11e6-9c6a-a25b653028c4.png)

**Comment by Ingiboy** [comment]
Хоп, все ок, автофокус довнес
