### ISSUE TITLE
На странице всех статей стилизовать select2

### ISSUE THREAD

**Issue by Ingiboy** [mixrich/news#33]
На странице http://to.westsib.ru/allarticles/ стилизовать выбранные тэги и поле сделать без скругленных углов.

**Comment by mixrich** [comment]
обновление CSS должно помочь

**Comment by Ingiboy** [comment]
Убери еще, плз, скругление углов у поля, у нас его его нигде в дизайне

**Comment by Ingiboy** [comment]
а вот именно так выбранный тэг сделать много сложнее?
![image](https://cloud.githubusercontent.com/assets/20064139/20237448/36945dd2-a905-11e6-943d-319f484359ee.png)

**Comment by mixrich** [comment]
Хардкорненькое такое переопределение стилей получается, но примерно такое построить возможно. Обнови CSS, должно помочь, надеюсь. Работать сложно, когда элементов локально нет, приходится делать с консоли и потом переносить в стили

**Comment by Ingiboy** [comment]
Ты крут) Все ок
