### ISSUE TITLE
Добавить снизу справа кнопку «НАВЕРХ» для скроллинга к шапке

### ISSUE THREAD

**Issue by Ingiboy** [mixrich/news#36]
Панель слева неудобна.

**Comment by mixrich** [comment]
от Артёма нужна картинка, где именно будет располагаться и как будет выглядеть + какие эффекты при hover и клике. Будем подключать какой-нибудь плавный скролл наверх?

**Comment by mixrich** [comment]
Обновить CSS, обновить app.js, вставить вот эту верстку на все страницы

`<div id="to-the-top" class="to-the-top">   
            <div class="to-the-top__icon"></div>   
            <div class="to-the-top__text">Вверх</div>   
        </div>`

**Comment by Ingiboy** [comment]
Кнопа появляется. Сделай, плз, её полупрозрачной и убери надпись «вверх».
На мобильной пока не срабатывает в УЦбраузере, если что)

**Comment by mixrich** [comment]
не появляется или не скроллится на клик?

**Comment by Ingiboy** [comment]
В мобильном - не появляется.
По виду - выглядит некрасиво.
Я думал примерно про такое
![image](https://cloud.githubusercontent.com/assets/20064139/20237569/e6277056-a908-11e6-8851-e4b3699d56e8.png)
или такое
![image](https://cloud.githubusercontent.com/assets/20064139/20237570/f77ef1d0-a908-11e6-90f2-daefdd5b84f1.png)

**Comment by Ingiboy** [comment]
так, кэш просрался, в мобильном хроме появилась и работает, в уцбраузере - нет, но я не уверен, что это не из-за кеша
пока поменяем кнопу на другую и ок

**Comment by mixrich** [comment]
На какую из?

**Comment by Ingiboy** [comment]
решили на эту
![image](https://cloud.githubusercontent.com/assets/20064139/20237608/e14fe954-a909-11e6-91e9-6054de826adf.png)

**Comment by mixrich** [comment]
Есть ссылка на эту иконку в SVG?

**Comment by Ingiboy** [comment]
увы, я поискал в гугле по картинкам

**Comment by mixrich** [comment]
1 Такая есть http://www.flaticon.com/free-icon/arrow-in-circle-point-to-up_10442
2 Такая http://www.flaticon.com/free-icon/up-button_26049
3 http://www.flaticon.com/free-icon/up-arrow_106804
4 http://www.flaticon.com/free-icon/upload_130886

**Comment by Ingiboy** [comment]
http://www.flaticon.com/free-icon/arrow-in-circle-point-to-up_10442
вот эту
и полупрозрачную, чтобы не была такой вопиюще черной

**Comment by mixrich** [comment]
кнопка круглая как и иконка?

**Comment by Ingiboy** [comment]
ага

**Comment by mixrich** [comment]
Обнови CSS и app.js, из верстки выкинь div с текстом, оставь только `<div id="to-the-top" class="to-the-top">
            <div class="to-the-top__icon"></div>
        </div>`

Если сейчас в UC не появится, то тогда я не знаю что сделать можно, ибо jQuery методы самые обычные используются

**Comment by Ingiboy** [comment]
Я подозреваю, что в УЦ работает кеширование.
В хромах обоих - ок.
В мобильной версии диаметр в 2 раза больше сделай, плз, а то мелкая сильно, и ок будет

**Comment by mixrich** [comment]
Готово

**Comment by mixrich** [comment]
Если бы UC браузер не просил у меня доступ к моей внутренней памяти и чему-то еще (не помню чему), то я бы его себе установил, а так я не понимаю зачем браузеру такие разрешения, учитывая что другие браузеры работают без них

**Comment by Ingiboy** [comment]
Отлично
