### ISSUE TITLE
В подвале при ховере некоторые ссылки жирнеют

### ISSUE THREAD

**Issue by Ingiboy** [mixrich/news#37]
![image](https://cloud.githubusercontent.com/assets/20064139/20183657/a88fac8e-a798-11e6-8773-f7dec8c2b008.png)

**Comment by mixrich** [comment]
Убрал жирность. Дело в том, что из-за мелкого размера и контраста цветов выглядит этот hover эффект на элементах подвала так себе... Посмотри, как тебе сейчас без жирности
