### ISSUE TITLE
ТАки перенести шрифты на сайт

### ISSUE THREAD

**Issue by Ingiboy** [mixrich/news#38]
Сейчас некоторые траблы с инетом, поэтому всё грузится быстро, а из-за шрифтов тормоза.
Логика, наверное, будет такой - если либо весь сайт тормозно грузится, либо сторонние цдн не создают проблем

**Comment by mixrich** [comment]
Разгадал откуда шли лохматые шрифты - мы брали один шрифт, например regular и пытались использовать его везде, в том числе и для жирного текста, тем самым растягивая текст и наблюдая косяки растяжения (как если картинку 640*480 тянуть на FullHD).

Выкачал все шрифты из мозилы и подключил их так же  как она - всего подключено 20 разновидностей Fira Sans. Сразу успокою тебя - грузятся не все 20 шрифтов. Если оставить только один, будут проблемы со сглаживанием, поэтому подключаем все 20, а там браузер уже разберется, какие где использовать и подгрузит только нужные. В частности у нас на главной грузится только regular и bold шрифты, возможно какие-то еще понадобятся для каких-либо браузеров, поэтому подключил все.

Что нужно сделать:
1. Скачать шрифты [fonts.zip](https://github.com/mixrich/news/files/587660/fonts.zip)
2. Закинуть их в папку /fonts/, ибо в CSS пути идут от /fonts/
3. Обновить CSS

**Comment by Ingiboy** [comment]
Гут. Готово
