### ISSUE TITLE
Куча css-мелочей

### ISSUE THREAD

**Issue by Ingiboy** [mixrich/news#39]
1. У даты сделать отступ снизу такой же, как и сверху. Сделать класс для неё
![image](https://cloud.githubusercontent.com/assets/20064139/20245045/add977dc-a9c9-11e6-852b-fe2d0f2c3af5.png)

2. Сделать класс для списка тэгов в конце материала:
![image](https://cloud.githubusercontent.com/assets/20064139/20245051/cb858b72-a9c9-11e6-9fae-451bd59f1546.png)
Сейчас там:
```
<div style="margin-top: 20px; margin-bottom: 40px;">
	Тэги/темы: 
	<ul class="article-tags">
		<li><a href="/tags/read/5">Томские новости</a></li>			</ul>
</div>
<style>
	.article-tags li + li:before {content: ", ";}
	.article-tags {display: inline; list-style: none;}
	.article-tags li {display: inline;}
</style>
```

3. Внести в css класс для списка тэгов на странице http://to.westsib.ru/tags/
Сейчас там:
```
<style>
	.taglist li + li:before {content: ", ";}
	.taglist {display: inline; list-style: none;}
	.taglist li {display: inline;}
	.taglist h4 {margin-top: 10px;}
</style>
```

**Comment by Ingiboy** [comment]
на [изменить]  внимания не обращай, это показывается если юзер админ

**Comment by mixrich** [comment]
Метрика добавляет отступ снизу http://prntscr.com/d711t1

**Comment by mixrich** [comment]
/article/507528 отступ от картинки до подписи больше чем от подписи до следующего элемента. Проверить что с этим можно сделать

**Comment by Ingiboy** [comment]
> /article/507528 отступ от картинки до подписи больше чем от подписи до следующего элемента. Проверить что с этим можно сделать

Где именно?

**Comment by Ingiboy** [comment]
> Метрика добавляет отступ снизу http://prntscr.com/d711t1

Точно. Как победить?

**Comment by mixrich** [comment]
1. Задал для всех article > div отступ снизу в 15 пикселей. У кого нет отступа - появится, у кого есть свой - свой и должен остаться
2. В блоке  

```
<div style="margin-top: 20px; margin-bottom: 40px;">
            Тэги/темы: 
            <ul class="article-tags">
                <li><a href="/tags/read/43">Про еду</a></li>
                                 <li><a href="/tags/read/381">Философия еды</a></li>
            </ul>
        </div>
```

меняем первую строчку на `<div style="article-tags-container">`, остальное остается как есть, стили перенес.
3. Перенес.
4. По метрике вроде в обед все решили

Надо CSS обновить
