### ISSUE TITLE
Внедрить подержку Legacy кода в статье

### ISSUE THREAD

**Issue by mixrich** [mixrich/news#4]
https://obzor.westsib.ru/news/504514/c6fbfb856853d888ab28975e57f0bc38

**Comment by mixrich** [comment]
Что удалось:
Взят этот блок 
![image](https://cloud.githubusercontent.com/assets/5591365/19012074/d650e9e6-87d4-11e6-8696-2c1b906f5177.png)
 и сделать на его верстке вот эти блоки
![image](https://cloud.githubusercontent.com/assets/5591365/19012080/04132254-87d5-11e6-9912-674003a0c158.png)

Из этого блока
![image](https://cloud.githubusercontent.com/assets/5591365/19012086/27587cb4-87d5-11e6-8425-9471c7d20d74.png)
получилось только притянуть за уши вот этот 
![image](https://cloud.githubusercontent.com/assets/5591365/19012094/4352a3ae-87d5-11e6-9136-464ef6720841.png)
И то, только если img будет не внутри p, а перед ним. Опять же, по семантике это не совсем тот самый блок, поэтому я не знаю корректно ли было такое legasy.

Далее уже нужно согласовать:
1. Из этого блока
![image](https://cloud.githubusercontent.com/assets/5591365/19012100/8acb63ba-87d5-11e6-9692-653a76a77980.png)
 я могу сделать либо такой заголовок
![image](https://cloud.githubusercontent.com/assets/5591365/19012103/99dc1502-87d5-11e6-9d82-5646d5ba9a65.png)
либо такой 
![image](https://cloud.githubusercontent.com/assets/5591365/19012107/a29a8fc0-87d5-11e6-8a79-2a97751b0bf5.png)
но только какой-то один из них.
Собственно, какое преобразование мы делаем? Принять решение поможет текст ниже.

Проблема: 
1. Другие элементы, вроде этого
![image](https://cloud.githubusercontent.com/assets/5591365/19012114/d59ab5b2-87d5-11e6-886c-61ab2b4cc7e1.png)
и одного из заголовков выше брать по сути не из чего и придется делать свои компоненты.

Возможное решение:
Я могу сделать стили для h3 и line2 отдельно, убрать у h3 отступ и тогда, если в редакторе в любом месте вручную сделать
`<h3></h3>
<div class="line2"></div>`
, то визуально это будет выглядеть как 
![image](https://cloud.githubusercontent.com/assets/5591365/19012141/aaf4c00e-87d6-11e6-9925-6858a1a81ba2.png)
и тогда вопрос, какой же блок заголовка делать как legasy, отпадает сам собой.
Ну и ссылку на статью автора
![image](https://cloud.githubusercontent.com/assets/5591365/19012147/d82fcde8-87d6-11e6-8612-3513de4cc606.png)
 могу попробовать сделать из
![image](https://cloud.githubusercontent.com/assets/5591365/19012151/e305f4a4-87d6-11e6-8d4a-4b7fb4159568.png)
, тем самым покрыв lagasy версткой все элементы нового дизайна.

Собственно, Игорь, нужно твое мнение, насколько это приживется в новом дизайне и насколько это поломает существующие статьи.

**Comment by Ingiboy** [comment]
Решено: адаптируем стили старых блоков к новой верстке, по возможности сохраняя их старый вид.
Новые блоки делаем как новые, с нуля.

**Comment by mixrich** [comment]
Перекочевал и адаптировал стили под новую верстку. Структура блоков не поменялась.
Осталось мобильную версию сделать

**Comment by mixrich** [comment]
Структуру обсуждаемых блоков взял, стили вытянул с сайта, адаптировал под новую верстку и современные адекватные стили (заливка вместо фоновой картинки, например). Написал для блоков мобильные стили.
