### ISSUE TITLE
Сделать отступ сверху над картинкой такой же, как и в правой колонке

### ISSUE THREAD

**Issue by Ingiboy** [mixrich/news#40]
![image](https://cloud.githubusercontent.com/assets/20064139/20259940/f6fa8512-aa89-11e6-9191-18ac86e21268.png)

**Comment by Ingiboy** [comment]
Логика размещения фото:

![image](https://cloud.githubusercontent.com/assets/20064139/20260109/c0801ece-aa8a-11e6-9f89-f08dce910d3f.png)

**Comment by mixrich** [comment]
Сделал такой же отступ. 
Мда, сайт с пустыми блоками aside и рекламой сверху смотрится немного не так уже)
