### ISSUE TITLE
Изменить вид кнопки шаринга twitter

### ISSUE THREAD

**Issue by Ingiboy** [mixrich/news#42]
![image](https://cloud.githubusercontent.com/assets/20064139/20280599/b6a12dee-aadf-11e6-9efa-9484406cd60d.png)

У твиттера нет счетчика

**Comment by mixrich** [comment]
Тут два пути - просто убрать счетчик у твиттера, либо воспользоваться вот этим сервисом https://opensharecount.com.

Я бы назвал это фичей, а не багом)

**Comment by Ingiboy** [comment]
Не хочу сервисы, на прошлой версии стояли они - тянут кучу дерьма, это сильно замедляет загрузку сайта.
Можно сделать отдельный класс на твиттер, блоки выводятся куском, я могу для каждого персонально что угодно прописать, а js-ка привязывается к идентификаторам.

**Comment by mixrich** [comment]
Обнови CSS

**Comment by Ingiboy** [comment]
Отлично
