### ISSUE TITLE
Уменьшить шрифты заголовков для десктопа

### ISSUE THREAD

**Issue by Ingiboy** [mixrich/news#44]
1. Уменьшить заголовок на материале
2. Уменьшить крупный заголовок в ленте новостей: https://obzor.westsib.ru/allnews/
3. Возможно уменьшить размер H3
Всё это - на десктопах

**Comment by Ingiboy** [comment]
Посмотрели еще - в статьях заголовки здоровые можно оставить.
В новостях - уменьшить до font-size:40px, line-height:50px;

**Comment by Ingiboy** [comment]
H3 - все равно уменьшить

**Comment by Ingiboy** [comment]
если у заголовка будет класс header-news и header-article, то я автоматом буду подставлять

**Comment by mixrich** [comment]
Блин, чет я запутался. Не мог бы ты скринами показать какой заголовок до какого размера уменьшить?

**Comment by Ingiboy** [comment]
**Заголовок новости, НЕ СТАТЬИ:**

```
font-size: 48px;
line-height: 60px;
```

Для этого можно сделать .header-article с текущими параметрами и .header-news с уменьшенными

**Заголовок H3 в тексте:**

```
font-size: 28px;
line-height: 36px;
```

**Заголовок H3 с флероном:**
![image](https://cloud.githubusercontent.com/assets/20064139/20461723/ffb5e99a-af38-11e6-8c0c-0bd02a230d60.png)
то же, что и у H3 +

```
margin-top: 30px;
```

**Comment by Ingiboy** [comment]
rss_important > rss_title:

```
font-size: 24px;
line-height: 32px;
```

**Comment by mixrich** [comment]
Вроде все отработал, даже создал оба класса header-article и header-news.

Если что-то не так понял или упустил, пиши)

Обнови CSS

**Comment by Ingiboy** [comment]
У Н1 не сработало
![image](https://cloud.githubusercontent.com/assets/20064139/20600349/c9fd037e-b285-11e6-835b-c804535d61c2.png)

**Comment by mixrich** [comment]
Готово
