### ISSUE TITLE
Посмотреть что можно сделать со слайдером в CKEditor-e (4.5.11)

### ISSUE THREAD

**Issue by Ingiboy** [mixrich/news#45]
Сейчас он выглядит вот так: 
![image](https://cloud.githubusercontent.com/assets/20064139/20343550/68833a92-ac21-11e6-8328-45976e314003.png)

Картинки показываются полноразмерные, поэтому если какая-то больше, чем блок, то получается порнография, плюс очень неочевидно перемещаться с одной на другую внутри, учитывая, что показывается только кусок группы фото).

Нижнее фото в блоке - вертикалка, от него видна только треть. Если все фото большие, то редактирование идет наощупь.

**Comment by mixrich** [comment]
Заведу локально у себя ckeditor, посмотрю к чему можно завязаться, чтобы стили для него переопределить. Не должно быть сложностей

**Comment by Ingiboy** [comment]
Для контентной области кэдитора подключается цсска с сайта. У нас на сервере стоит модуль склейки статики, это дает возможность тонну цсс и жс отдавать одним файлом:
`<link rel="stylesheet" href="/css/??style.base.css,style.addon.css,mistakes.css?0001" charset="utf-8">`
`<script src="/js/??mistakes.js,jquery-1.12.4.min.js,jquery.onscreen.min.js,goodshare.min.js,slick.min.js,app.js,r-westsib-ru.js?0001"></script>`

Поэтому можно сделать отдельный цсс для коррекции стилей для показа в кэдиторе, а я их подключу как один файл
`config.contentsCss = '/css/??style.base.css,_STYLE_FOR_ADMIN_.CSS,jquery.spellchecker.min.css';`

Могу еще дать свою сборку кэдитора уже с плагинами для блоков, см.телеграм, гитхаб не понимает мой зип

**Comment by mixrich** [comment]
Идея с отдельной админской CSS мне нравится, ее и опробуем

**Comment by mixrich** [comment]
Запушил файл `style.ckeditor.css`, который чинит слайдер в админке и делает его в виде серого полотна с фотками http://prntscr.com/d9huzv, где фотки высотой 100px. Полотно растягивается от содержимого, поэтому влезет хоть сколько фоток, пробуй)

**Comment by Ingiboy** [comment]
Красота)
