### ISSUE TITLE
Типографика - привести в порядок

### ISSUE THREAD

**Issue by mixrich** [mixrich/news#46]
Пройтись по статьям, понять где отступы нужны, а где не нужны.
Касательно картинок вроде этих http://prntscr.com/d9i0wf, когда в самом редакторе выставляется позиционирование и размеры, надо бы в мобильнике их тянуть на всю ширину, или настроить max-width, чтобы как только размер кэрана меньше картинки, она уменьшалась. Сейчас на мобиле это выглядит так http://prntscr.com/d9i1b2

**Comment by Ingiboy** [comment]
Если картинка прижата вправо, то отступы 0 20рх 20рх 0, если влево, то 0 0 20рх 20рх.
Остальное вроде бы у тебя правильно написано, уточняй, если есть еще моменты

**Comment by mixrich** [comment]
если картинка будет 400 шириной, то она просто не влезет в мобилу в текущем состоянии.

**Comment by Ingiboy** [comment]
Тогда ужимать, да. Не знаю, насколько это выполнимо, скажи

**Comment by mixrich** [comment]
Картинки из редактора в мобиле пофиксил, обновляй CSS

**Comment by Ingiboy** [comment]
актуализировать костыль:
```
.cke_editable .slider img {
    height: 100px !important;
    width: auto;
}
```
