### ISSUE TITLE
Адаптировать старую отбивку одиноким листочком

### ISSUE THREAD

**Issue by Ingiboy** [mixrich/news#47]
![image](https://cloud.githubusercontent.com/assets/20064139/20602186/b373d048-b28e-11e6-9d8b-1d75f39a9639.png)
Загнать этот листочек в 
```
<div class="line3"></div>
```
Чтобы он был без линий по бокам по центру
И clear:both; не забыть)

**Comment by mixrich** [comment]
Готово, обновляй CSS
