### ISSUE TITLE
СРОЧНО! В тексте нет офомления для UL и OL

### ISSUE THREAD

**Issue by Ingiboy** [mixrich/news#49]

**Comment by mixrich** [comment]
Ага, только что вспомнил про них сам, добавлю вечером

**Comment by mixrich** [comment]
Добавил. Есть что доработать, поэтому пока не закрывай

**Comment by Ingiboy** [comment]
Поехали li тэгов из-за списков) надо им отдельный класс сделать наверное
![image](https://cloud.githubusercontent.com/assets/20064139/20978418/692c9914-bcdb-11e6-8a2b-530dc1f56496.png)

![image](https://cloud.githubusercontent.com/assets/20064139/20978429/76475c92-bcdb-11e6-84d4-a9663851e9ef.png)

**Comment by mixrich** [comment]
У них и был класс, просто стили статьи дополняли его отступами. Починил, обновляй css

**Comment by Ingiboy** [comment]
Под текстом материала отступы остались.

![image](https://cloud.githubusercontent.com/assets/20064139/21072058/990c1074-bee8-11e6-9692-ce7e0973c836.png)

**Comment by mixrich** [comment]
А сейчас?

**Comment by Ingiboy** [comment]
Спасибо, сейчас ок, если больше ничего не осталось - закрывай
