### ISSUE TITLE
Мелкие баги

### ISSUE THREAD

**Issue by mixrich** [mixrich/news#5]
- http://prntscr.com/cojx7p

**Comment by Ingiboy** [comment]
`<div class="line3"> </div>` - нет в стилях и не адаптирован, соответственно

**Comment by Ingiboy** [comment]
**Заголовки H3 в тексте мелко выглядят и межстрочный интервал маловат:**

![image](https://cloud.githubusercontent.com/assets/20064139/19230433/a318976e-8efe-11e6-98d8-5d07250da521.png)

**А при переключении в мобильное представление - хорошо:**

![image](https://cloud.githubusercontent.com/assets/20064139/19230423/972999ee-8efe-11e6-9917-ea80f9fcbb15.png)

**Comment by Ingiboy** [comment]
Картинки не уменьшаются

![image](https://cloud.githubusercontent.com/assets/20064139/19232073/e2b26c48-8f07-11e6-8e0c-149393bfc91d.png)

Это из-за вписанных размеров? Можно ли заставить браузер игнорировать то, что вписано в стилях у картинок? Это плагин для CKeditor вставляет размеры

==================================== Responce
Да, это из-за того, что ckeditor вставляет размеры. Плохо то, что он вставляет картинки в параграф, а это не совсем предсказуемое для нас поведение. Залил в style.base.css решение, должно помочь в таких случаях

**Comment by mixrich** [comment]
Отступа нет http://prntscr.com/cs1hfn

**Comment by Ingiboy** [comment]
> Отступа нет http://prntscr.com/cs1hfn

Ага. А в мобильном - есть, и шрифт крупнее.
