### ISSUE TITLE
Статья. Слайдер

### ISSUE THREAD

**Issue by temadorokhov** [mixrich/news#6]
Внутри слайдера фотографии должны быть выровнены по вертикальному и горизонтальному центру. Т.е. вот в такой ситуации: http://take.ms/0X9Dg — фотка должна быть по вертикальному центру, а не по верху. С портретной фоткой такая же история, она должна быть выровнена по центру (между стрелочками)

**Comment by mixrich** [comment]
Тут вопрос в поддержке браузерами, ибо кроссбраузерного общего способа выровнять картинку в блоке не существует.:
Способ 1: Оборачиваем каждую картинку в дополнительный div, используем новомодные свойства flex и flexbox, покрываем в принципе все мобильный браузеры, на компе только IE10+. Поскольку IE9 в мире 0.1%, способ самый приемлемый, но нужна дополнительная div вокруг картинок.
Способ 2: Без дополнительной обертки, только картинки со свойством object-fit. Этот способ считаю совсем уж не приемлемым, ибо IE никакой вообще не поддерживается, в нем картинки будут тянуться и ломать свои пропорции до указанный в стилях. Зато никакой обертки не надо, а в мобильных устройствах это свойство не будет использоваться.

**Comment by Ingiboy** [comment]
У нас вот такая статистика по посещениям за последний квартал. Годовая примерно такая же.
[Статистика](https://api.monosnap.com/rpc/file/download?id=6XbRiOKc41RBvFz5U3pSPubumFNlr7)

Человеков с ИЕ8 4500 набирается, многовато для пожертвования. 

Есть ли способ №3 - чуть допилить слайдер, чтобы он программно каждую картинку оборачивал с нужный div?

**Comment by mixrich** [comment]
Фига, и правда с IE8 заходят.... 
Допилить всегда можно, если сроки не жмут, могу сам этим заняться и допилить программную обертку.

**Comment by Ingiboy** [comment]
Итого, какой способ нам лучше всего подойдет, учитывая статистику?

**Comment by mixrich** [comment]
Вообще, если встал вопрос про IE8, то тут однозначно что-то сложно сказать, ибо сам сайт в целом придется нехило так подогнать под него, ибо много артефактов вылезет. 
Программно оборачивать каждый слайд в div, наверное, самый оптимальный вариант. Да, придется написать дополнительный код и подумать о совместимостях, зато ошибки со стороны контентщиков (вдруг забудут обернуть) мы исключим

**Comment by Ingiboy** [comment]
У меня вопрос - можно ли сделать так, чтобы в случае неподдерживаемого ИЕ фотки в блоке слайдера выстраивались в колонку с пропорциональным уменьшением по ширине страницы, а в случае с нормальными браузерами - включался режим слайдера?
Для нас это допустимо.

**Comment by mixrich** [comment]
ИЕ 9 поддерживается сайтом, ИЕ8 сайтом не поддерживается. Многие вещи, а самое главное - адаптивность - просто не сделать, если помнить про ИЕ8. Придется его отпустить и относиться к нему как к истории. 

Фотки теперь везде показываются нормально, нашел способ выравнивать их кроссбраузерно. 
Через JS оборачиваю их в нужный контейнер, так что контентщикам не нужно ни о чем думать, просто накидывать фотки внутрь div.slider.

Решение готово
