### ISSUE TITLE
Добавить datePicker

### ISSUE THREAD

**Issue by mixrich** [mixrich/news#8]

**Comment by mixrich** [comment]
Спустя долгие выбирания и страдания, остановился на этом https://github.com/dbushell/Pikaday. 
Из коробки не очень симпотный, но неплохая поддержка браузеров (IE8+), по вертке своей тоже очень простой, стили кастомизируются.
Язык русский ему можно подпихнуть в общепринятом стандарте, настроек тоже много., зависимостей никаких лишних

**Comment by Ingiboy** [comment]
мне нравится, тоже заюзаю
